config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/offenders/:jurisdiction/:id' => 'offenders#show', as: :offender
  post '/offenders/:jurisdiction' => 'offender_jurisdictions#search'
  get '/offenders/:jurisdiction' => 'offender_jurisdictions#show', as: :offender_jurisdiction
  get '/offenders/:id', to: redirect('/offenders/oregon/%<id>') # deprecated!

  get '/offenders', to: 'offender_jurisdictions#index', as: :offenders
  post '/offenders/:jurisdiction', to: 'offender_jurisdictions#search'

  get '/feedback/:id' => 'feedback_responses#show', id: /\d+/
  get '/feedback/:type' => 'feedback_responses#create', as: :feedback_response
  patch '/feedback/:id' => 'feedback_responses#update'

  namespace :admin do
    resources :digital_vrns, only: %i[index show]
    resource :import_status, only: %i[show]
  end

  resources :rights, only: %i[show index create destroy], id: Regexp.union(RightsFlow::PAGES) do
    collection do
      post '/:id', to: 'rights#update'
      delete '/', to: 'rights#delete'
      get '/preview', to: 'rights#preview'
    end
  end

  resources :faqs, only: %i[show index]

  resources :mailchimp_csvs, only: %i[show]

  resource :styleguide, only: %i[show]

  resource :sessions, only: %i[new create destroy]
  resources :users, only: %i[edit update]

  get '/t/:tracking_id', to: 'home#set_tracking'

  get '/trigger-error', to: 'home#trigger_error'
  get '/sandbox', to: 'home#sandbox'
  get '/health', to: 'home#health'
  get '/home', to: 'home#home'

  root to: 'home#splash'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  REVISION_PATH = File.expand_path('../../REVISION', __FILE__)

  def splash
    return redirect_to home_path if @current_user

    render layout: 'splash'
  end

  def home
    return redirect_to root_path unless @current_user.is_admin?

    # Admin-only stuff:
    @data_ranges = {}

    begin
      local_crimes = LocalCrimesInPostgres.new
      @data_ranges = local_crimes.data_range
    rescue => ex
      Raven.capture_exception(ex)
    ensure
      local_crimes.close if local_crimes
    end
  end

  def set_tracking
    session[:distinct_id] = params[:tracking_id].to_i
    redirect_to root_path
  end

  def trigger_error
    raise 'Sentry testing error!'
  end

  def health
    info = {
      revision: File.exist?(REVISION_PATH) ? File.read(REVISION_PATH) : 'unknown',
    }

    render json: info
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/_logged_out.html.haml
- content_for :page_title do
  = t('product_description')

app/views/home/_user.html.haml
.row
  .col.s12
    %h2.app-typography--header-1 Hello #{current_user.email}
    %p
      You are logged in.
    %p
      This is a placeholder for whatever you see when you log in.

    = link_to 'Log Out', sessions_path, method: :delete

app/views/home/home.html.haml
.row.app-row
  .col.s12
    %h2.app-typography--header-1 Hello #{@current_user.email}
    %p
      You are logged in.

- if @current_user.is_admin?
  .row.app-row
    .col.s12
      Admin Options:
      - MailchimpCsvGenerator::CSVS.keys.each do |key|
        - range = @data_ranges[key]
        - if range && range.min && range.max
          %p= link_to "Download #{key.titleize} Mailchimp CSV", mailchimp_csv_path(key)
          %ul.browser-default
            %li= t("home_logged_in.email_description.#{key}", start: range.min.to_date, end: range.max.to_date)
        - else
          %p There was an error importing #{key.titleize} data.

      %p= link_to 'Download VRN Confirmation PDFs', admin_digital_vrns_path
      %p= link_to 'Debug Information', admin_import_status_path

.row.app-row
  .col.s12
    = link_to 'Log Out', sessions_path, method: :delete

app/views/home/index.html.haml
- if current_user
  = render 'user'
- else
  = render 'logged_out'

app/views/home/sandbox.html.haml
= stylesheet_link_tag 'sandbox'

.row
  .col.s10.offset-s1.m8.offset-m2
    %h1.app-typography--header-1 Sandbox Header

    %p Here is a haml sandbox with all our styles and everything!

    = render_component 'button' do
      Search

    %a.app-button
      &nbsp;
.row
  .col.s2.offset-s1


    / = render_component 'button' do
    /   Here is a button!
.row
  .col.s10.offset-s1.m8.offset-m2
    = render_component 'timeline'

app/views/home/splash.html.haml
- if @current_user
  = render 'user'
- else
  = render 'logged_out'