config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/offenders/:jurisdiction/:id' => 'offenders#show', as: :offender
  post '/offenders/:jurisdiction' => 'offender_jurisdictions#search'
  get '/offenders/:jurisdiction' => 'offender_jurisdictions#show', as: :offender_jurisdiction
  get '/offenders/:id', to: redirect('/offenders/oregon/%<id>') # deprecated!

  get '/offenders', to: 'offender_jurisdictions#index', as: :offenders
  post '/offenders/:jurisdiction', to: 'offender_jurisdictions#search'

  get '/feedback/:id' => 'feedback_responses#show', id: /\d+/
  get '/feedback/:type' => 'feedback_responses#create', as: :feedback_response
  patch '/feedback/:id' => 'feedback_responses#update'

  namespace :admin do
    resources :digital_vrns, only: %i[index show]
    resource :import_status, only: %i[show]
  end

  resources :rights, only: %i[show index create destroy], id: Regexp.union(RightsFlow::PAGES) do
    collection do
      post '/:id', to: 'rights#update'
      delete '/', to: 'rights#delete'
      get '/preview', to: 'rights#preview'
    end
  end

  resources :faqs, only: %i[show index]

  resources :mailchimp_csvs, only: %i[show]

  resource :styleguide, only: %i[show]

  resource :sessions, only: %i[new create destroy]
  resources :users, only: %i[edit update]

  get '/t/:tracking_id', to: 'home#set_tracking'

  get '/trigger-error', to: 'home#trigger_error'
  get '/sandbox', to: 'home#sandbox'
  get '/health', to: 'home#health'
  get '/home', to: 'home#home'

  root to: 'home#splash'
end

app/controllers/offender_jurisdictions_controller.rb
# frozen_string_literal: true

# rubocop:disable Metrics/AbcSize

class OffenderJurisdictionsController < ApplicationController
  include ActionView::Helpers::SanitizeHelper

  def index; end

  def show
    # if this page has an "error" query param then don't attempt a search and
    # just show that error
    case params[:error]
    when 'error_no_results'
      @search_error = I18n.t('offender_search.error_no_results',
        search_sid: params[:error_sid])
    when 'error_connection_failed'
      @search_error = I18n.t('offender_search.error_connection_failed')
    when 'error_offender_expired'
      @search_error = I18n.t('offender_search.error_offender_expired')
    end
  end

  def search
    if offender_params[:sid].present?
      # when searching for a SID, just go to /offenders/<sid> and let that page
      # do the search
      redirect_to offender_path(:oregon, offender_params[:sid])
      return
    end

    error = valid_offender_search?(params[:jurisdiction].to_sym)
    if error
      @search_error = error
      return render :show
    end

    # otherwise, do the search!

    @results = []

    if %w[dcj unknown].include?(params[:jurisdiction])
      # DCJ search requires last_name and (SID|dob) for now :(
      @results.push(search_dcj)
    end

    if %w[oregon unknown].include?(params[:jurisdiction])
      @results.push(*search_oregon)
    end

    @results.compact!

    @grouped_results = OffenderGrouper.new(@results)
    @name_highlighter = OffenderNameHighlighter.new(offender_params)

    @mixpanel.track('search',
      jurisdiction: params[:jurisdiction],
      num_results: @grouped_results.total_results,
      fields: offender_params.to_unsafe_hash)

    if @results.empty?
      full_name = sanitize("#{offender_params[:first_name]} #{offender_params[:last_name]}")

      case params[:jurisdiction].to_sym
      when :oregon
        @search_error ||= I18n.t(
          'offender_search.error_no_results_prison_by_name_html',
          name: full_name,
        ).html_safe
      when :dcj
        @search_error ||= I18n.t(
          'offender_search.error_no_results_dcj_by_name_html',
          name: full_name,
        ).html_safe
      end
    elsif @results.length == 1
      result = @results[0]
      return redirect_to offender_path(result[:jurisdiction], result[:sid])
    end

    render :show
  end

  private

  def valid_offender_search?(jurisdiction)
    case jurisdiction
    when :oregon
      # one of first_name, or last_name must be present
      unless offender_params[:first_name].present? || offender_params[:last_name].present?
        I18n.t('offender_search.error_missing_name')
      end
    when :dcj
      # last name and DOB must all be present
      unless offender_params[:last_name].present?
        return I18n.t('offender_search.error_missing_last_name')
      end

      unless offender_params[:dob][:year].present? &&
          offender_params[:dob][:month].present? &&
          offender_params[:dob][:day].present?
        return I18n.t('offender_search.error_missing_dob')
      end
    when :unknown
      # last name and dob are all required
      unless offender_params[:last_name].present?
        return I18n.t('offender_search.error_missing_last_name')
      end

      unless offender_params[:dob][:year].present? &&
          offender_params[:dob][:month].present? &&
          offender_params[:dob][:day].present?
        return I18n.t('offender_search.error_missing_dob')
      end
    end
  end

  def offender_params
    params.fetch(:offender, {})
  end

  def search_dcj
    offender_dob_year = offender_params[:dob][:year].to_i

    if offender_dob_year < 100 # "67" for "1967"
      offender_dob_year +=
        if offender_dob_year < Date.today.year % 100
          # if the short year is in the recent past, use current century
          2000
        else
          # if the short year is in the future, use previous century
          1900
        end
    end

    offender_dob = begin
                     Date.new(
                       offender_dob_year,
                       offender_params[:dob][:month].to_i,
                       offender_params[:dob][:day].to_i,
                     )
                   rescue
                     nil
                   end

    # sanity check the DOB that it is not too far in the past or in the future
    unless offender_dob && 120.years.ago < offender_dob && offender_dob < Date.today
      date_string =
        offender_params[:dob].values_at(:month, :day, :year).join('/')

      @search_error =
        I18n.t('offender_search.error_invalid_date', date: date_string)

      # Since DOB is required, may as well not do anything
      return
    end

    result = nil
    begin
      start_time = Time.now
      result = DcjClient.new.search_for_offender(
        dob: offender_dob,
        last_name: offender_params[:last_name],
      )
      @mixpanel.track('search-duration', duration: Time.now - start_time)
    rescue DcjClient::RequestError => ex
      Raven.capture_exception(ex)
      @search_error = I18n.t('offender_search.error_connection_failed')
    end

    result
  end

  def search_oregon
    # otherwise, time to search by name!
    results = []

    begin
      results = OffenderScraper.search_by_name(
        offender_params[:first_name],
        offender_params[:last_name],
      )
    rescue OosMechanizer::Searcher::ConnectionFailed
      @search_error = I18n.t('offender_search.error_connection_failed')
    rescue OosMechanizer::Searcher::TooManyResultsError
      @search_error = I18n.t('offender_search.error_too_many_results')
    end

    results
  end
end

app/helpers/offender_jurisdictions_helper.rb
# frozen_string_literal: true

module OffenderJurisdictionsHelper
  def search_params
    @_search_params ||=
      params.fetch(:offender, {}).slice(:first_name, :last_name)
  end

  def emphasized_text(text)
    content_tag(:span, text, class: 'app__header--emphasis')
  end
end

app/views/offender_jurisdictions/_dcj.html.haml
- content_for :page_title, t('offender_search.dcj_title')

= form_for :offender, url: offender_jurisdiction_path(:dcj) do |f|
  .row.app-row
    .col.s12
      = link_to t('offender_search.back'), offenders_path

      %h2.app-typography--header-1= raw(t('offender_search.title_jurisdiction',
        in: emphasized_text('on probation or parole')))

  - if @search_error
    .row.app-row.app-row--error
      .col.s12
        = mixpanel_track_message :error, @search_error
        = @search_error

  .row.app-row.app-row--with-separator
    .col.s12.m5
      .app-input-field
        = f.label :last_name, t('offender_search.last_name.label')
        = f.text_field :last_name

    = f.dob_select_field :dob

  .row.app-row.app-row--with-separator
    .col.s12
      = render_component 'button', spinner: true, submit: f do
        = t('offender_search.search')

app/views/offender_jurisdictions/_oregon.html.haml
- content_for :page_title, t('offender_search.oregon_title')

= form_for :offender, url: offender_jurisdiction_path(:oregon) do |f|
  .row.app-row
    .col.s12
      = link_to t('offender_search.back'), offenders_path

      %h2.app-typography--header-1= raw(t('offender_search.title_jurisdiction',
        in: emphasized_text('in prison')))

  - if @search_error
    .row.app-row.app-row--error
      .col.s12
        = mixpanel_track_message :error, @search_error
        = @search_error

  .row.app-row.app-row--with-separator
    .col.s12
      %h3.app-typography--header-2= t('offender_search.by_name')

    .col.s12.m5
      .app-input-field
        = f.label :first_name, t('offender_search.first_name.label'),
          class: ('active' if search_params[:first_name].present?)
        = f.text_field :first_name, value: search_params[:first_name]

    .col.s12.m5
      .app-input-field
        = f.label :last_name, t('offender_search.last_name.label'),
          class: ('active' if search_params[:last_name].present?)
        = f.text_field :last_name, value: search_params[:last_name]

    .col.s12
      = link_to 'Search by SID number', '#reveal-search-by-sid', class: 'app-reveal'

  .row.app-row.app-row--with-separator.hide#reveal-search-by-sid
    .col.s12
      %h3.app-typography--header-2= t('offender_search.by_sid')

    .col.s12.m5
      .app-input-field
        = f.label :sid, t('offender_search.sid.label')
        = f.text_field :sid

  .row.app-row.app-row--with-separator
    .col.s12
      = render_component 'button', spinner: true, submit: f do
        = t('offender_search.search')

app/views/offender_jurisdictions/_unknown.html.haml
- content_for :page_title, t('offender_search.title')

= form_for :offender, url: offender_jurisdiction_path(:unknown) do |f|
  .row.app-row
    .col.s12
      = link_to t('offender_search.back'), offenders_path

      %h2.app-typography--header-1= t('offender_search.title')

  - if @search_error
    .row.app-row.app-row--error
      .col.s12
        = mixpanel_track_message :error, @search_error
        = @search_error

  .row.app-row.app-row--with-separator
    .col.s12.m6
      .app-input-field
        = f.label :first_name, t('offender_search.first_name.label'),
          class: ('active' if search_params[:first_name].present?)
        = f.text_field :first_name, value: search_params[:first_name]

    .col.s12.m6
      .app-input-field
        = f.label :last_name, t('offender_search.last_name.label'),
          class: ('active' if search_params[:last_name].present?)
        = f.text_field :last_name, value: search_params[:last_name]

    = f.dob_select_field :dob

  .row.app-row.app-row--with-separator
    .col.s12
      = render_component 'button', spinner: true, submit: f do
        = t('offender_search.search')

app/views/offender_jurisdictions/index.html.haml
- content_for :page_title, t('offender_search.title')

.row.app-row
  .col.s12
    %h1.app-typography--header-1= t('offender_search.title')

.row.app-row.app-row--with-separator
  .col.s12.m6.offset-m3
    .app__search-button-holder
      = render_component 'button', to: offender_jurisdiction_path(:oregon), stretch: true do
        = t('offender.search_prison')

    .app__search-button-holder
      = render_component 'button', to: offender_jurisdiction_path(:dcj), stretch: true do
        = t('offender.search_probation')

    .app__search-button-holder
      = render_component 'button', to: offender_jurisdiction_path(:unknown), stretch: true do
        = t('offender.search_unknown')

app/views/offender_jurisdictions/show.html.haml
- case params[:jurisdiction].to_sym
- when :oregon
  = render 'offender_jurisdictions/oregon'
- when :dcj
  = render 'offender_jurisdictions/dcj'
- when :unknown
  = render 'offender_jurisdictions/unknown'

- if @results.present?
  .row.app-row
    - query = "#{search_params[:first_name]} #{search_params[:last_name]}"
    - bold_query = content_tag(:strong, query)

    .col.s12.hide-on-large-only
      %p.app-typography--body-2
        = raw(t('offender_search.num_results', num: @grouped_results.total_results, name: bold_query))

      - @results.each do |result|
        %div.app-card--result
          %ul
            %li
              %span.app-card--result__label.mdl-typography--caption SID
              = result[:sid]
            %li
              %span.app-card--result__label.mdl-typography--caption First
              = result[:first]
            %li
              %span.app-card--result__label.mdl-typography--caption Middle
              = result[:middle]
            %li
              %span.app-card--result__label.mdl-typography--caption Last
              = result[:last]
            %li
              %span.app-card--result__label.mdl-typography--caption DOB
              = result[:dob]
          = render_component 'button', to: offender_path(result[:jurisdiction], result[:sid]) do
            View offender
            = fa_icon 'angle-right'


    .col.s12.hide-on-med-and-down
      %p.app-typography--body-2
        = raw(t('offender_search.num_results', num: @grouped_results.total_results, name: bold_query))

    .hide-on-med-and-down
      %table.app-table.app-table--full-bleed.app-table--group-rows
        %thead
          %tr
            %th SID
            %th Known Aliases
            %th DOB
        - @grouped_results.each_group do |group|
          %tbody
            - path = offender_path(group[:jurisdiction], group[:sid])
            %tr.app-table__row--bordered{ data: { href: path } }
              %td= link_to group[:sid], path
              %td= @name_highlighter.highlight(group[:full_name])
              %td= group[:dob]
            - group[:aliases].each do |name|
              %tr{ data: { href: path } }
                %td
                %td= @name_highlighter.highlight(name)
                %td