config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/offenders/:jurisdiction/:id' => 'offenders#show', as: :offender
  post '/offenders/:jurisdiction' => 'offender_jurisdictions#search'
  get '/offenders/:jurisdiction' => 'offender_jurisdictions#show', as: :offender_jurisdiction
  get '/offenders/:id', to: redirect('/offenders/oregon/%<id>') # deprecated!

  get '/offenders', to: 'offender_jurisdictions#index', as: :offenders
  post '/offenders/:jurisdiction', to: 'offender_jurisdictions#search'

  get '/feedback/:id' => 'feedback_responses#show', id: /\d+/
  get '/feedback/:type' => 'feedback_responses#create', as: :feedback_response
  patch '/feedback/:id' => 'feedback_responses#update'

  namespace :admin do
    resources :digital_vrns, only: %i[index show]
    resource :import_status, only: %i[show]
  end

  resources :rights, only: %i[show index create destroy], id: Regexp.union(RightsFlow::PAGES) do
    collection do
      post '/:id', to: 'rights#update'
      delete '/', to: 'rights#delete'
      get '/preview', to: 'rights#preview'
    end
  end

  resources :faqs, only: %i[show index]

  resources :mailchimp_csvs, only: %i[show]

  resource :styleguide, only: %i[show]

  resource :sessions, only: %i[new create destroy]
  resources :users, only: %i[edit update]

  get '/t/:tracking_id', to: 'home#set_tracking'

  get '/trigger-error', to: 'home#trigger_error'
  get '/sandbox', to: 'home#sandbox'
  get '/health', to: 'home#health'
  get '/home', to: 'home#home'

  root to: 'home#splash'
end

app/views/layouts/_analytics_js.html.haml
:javascript
  window.CaseCompanion = window.CaseCompanion || {};
  window.CaseCompanion.mixpanel = #{JSON.generate(
    token: @mixpanel_token,
    distinct_id: session[:distinct_id],
  ).html_safe};

- if inspectlet_record?
  :javascript
    window.__insp = window.__insp || [];
    __insp.push(['wid', 1199690806]);
    (function() {
    function ldinsp(){if(typeof window.__inspld != "undefined") return; window.__inspld = 1; var insp = document.createElement('script'); insp.type = 'text/javascript'; insp.async = true; insp.id = "inspsync"; insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cdn.inspectlet.com/inspectlet.js'; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(insp, x); };
    setTimeout(ldinsp, 500); document.readyState != "complete" ? (window.attachEvent ? window.attachEvent('onload', ldinsp) : window.addEventListener('load', ldinsp, false)) : ldinsp();
    })();

- if ENV['GOOGLE_ANALYTICS_SITE_ID'].present?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', #{JSON.generate(ENV['GOOGLE_ANALYTICS_SITE_ID']).html_safe}, 'auto');


:javascript
  (function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
  0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
  for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
  mixpanel.init(window.CaseCompanion.mixpanel.token);

  if (window.CaseCompanion.mixpanel.distinct_id) {
    mixpanel.identify("user-" + window.CaseCompanion.mixpanel.distinct_id);
  }

app/views/layouts/_footer.html.haml
%section.app-footer
  .app-container
    .row.app-row
      .col.s12.l6
        %h3.app-typography--section-heading.app-typography--header-2= t('footer.title')

        %ul.app-footer__feedback-list
          - current_path = request.path
          %li= link_to 'Yes', feedback_response_path(type: :thumbs_up, page: current_path), target: '_blank'
          %li= link_to 'No', feedback_response_path(type: :thumbs_down, page: current_path), target: '_blank'
          %li= link_to 'Yes, but', feedback_response_path(type: :yes_but, page: current_path), target: '_blank'

      .col.s12.l6
        %p.app-footer__powered-by
          = render_component 'logo'
          = t('footer.powered_by_html')

      .col.s12
        %span.app-footer__powered-by= t('footer.disclaimer')

app/views/layouts/_meta_tags.html.haml
%meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
%meta{ name: 'description', content: t('product_description') }
%meta{ 'http-equiv' => 'Content-Type', content: 'text/html; charset=utf8' }
= csrf_meta_tags

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= page_title

    = render 'layouts/meta_tags'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/analytics_js'

  %body
    %header.app-header
      .app-container
        .row
          .col.s10.offset-s1.m8.offset-m2
            %h1.app-header__title
              = link_to root_path, class: 'app-header__logo' do
                = render_component 'logo'

    %main.app-container--main
      - if content_for?(:pre_main_focus)
        .app-container.app-container--pre-main-focus
          = yield :pre_main_focus

      - if flash[:info]
        .row
          .col.s10.offset-s1.m8.offset-m2
            = simpler_format flash[:info]
            = mixpanel_track_message :info, flash[:info]

      - if flash[:error]
        .row
          .col.s10.offset-s1.app-cell--error
            = simpler_format flash[:error]
            = mixpanel_track_message :error, flash[:error]

      = yield

    = render 'layouts/footer'

app/views/layouts/email.html.haml
= stylesheet_link_tag 'email'

%table.email--outer
  %tr
    %td.email--outer-cell

      %table.email--seal
        %tr
          %td
            = image_tag 'seal_DA.png', class: 'email--seal-img'
          %td
            %p.email--seal__title
              = t('email_layout.da_name')

            %ul.email--contact-details-list-small
              %li= t('email_layout.vap_name')
              %li= t('email_layout.vap_phone')
              %li= t('email_layout.vap_url')

  %tr
    %td.email--outer-cell
      = yield

  %tr
    %td.email--outer-cell
      - unless @remove_feedback_section
        %table.email--feedback
          %tr
            %td{ colspan: 3 }
              %h2= t('email_layout.footer_feedback_title')
          %tr
            %td{ width: '33%' }
              = link_to feedback_response_url('thumbs_up'), class: 'email--feedback-link' do
                %p= t('email_layout.footer_feedback_yes')
            %td{ width: '33%' }
              = link_to feedback_response_url('thumbs_down'), class: 'email--feedback-link' do
                %p= t('email_layout.footer_feedback_no')
            %td{ width: '33%' }
              = link_to feedback_response_url('yes_but'), class: 'email--feedback-link' do
                %p= t('email_layout.footer_feedback_yes_but')

      %h6.email--footer-our-address= t('email_layout.footer_address')

      %ul.email--footer-our-address-list
        %li= t('email_layout.footer_address_name')
        %li= t('email_layout.footer_address_address')
        %li= t('email_layout.footer_address_citystate')

app/views/layouts/focused.html.haml
!!! 5
%html
  %head
    %title= page_title

    = render 'layouts/meta_tags'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/analytics_js'

  %body
    .app-container--focused
      .app-container--focused__header= content_for(:header)

      = yield

      .app-container--focused__footer= content_for(:footer)

app/views/layouts/splash.html.haml
!!! 5
%html
  %head
    %title= page_title

    = render 'layouts/meta_tags'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/analytics_js'

  %body
    %header.app-header.app-header--hero
      .app-container
        .row
          .col.s8.offset-s2
            = link_to root_path do
              %h1.app-header__title--splash= render_component 'logo', variant: :single_color
            .app-header__subtitle formerly MyAdvocate

      .app-container
        .row
          .col.s8.offset-s2
            %h2.app-header__headline= t('home.headline')
            %h3.app-header__subhead-1= t('home.subhead_1')
            %h3.app-header__subhead-2= t('home.subhead_2')

    .app-header
      .app-container.app-container--left-line.app-container--subhero
        .row
          .col.s8.offset-s2
            %h3.app-typography--display-2= t('home.timeline_header')

        .row.app-row--left-line-dot
          .col.s8.offset-s2
            %h3.app-typography--header-1= t('home.after_reporting.header')

            .app-home-link-with-description
              = link_to t('home.after_reporting.what_happens.link'),
                faqs_path(anchor: 'what-happens-after-reporting-a-crime'),
                class: 'app-typography--body-1'
              .app-typography--body-2= t('home.after_reporting.what_happens.description')

        .row.app-row--left-line-dot
          .col.s8.offset-s2
            %h3.app-typography--header-1= t('home.after_charges.header')

            .app-home-link-with-description
              = link_to t('home.after_charges.request_rights.link'), rights_path, class: 'app-typography--body-1'
              .app-typography--body-2= t('home.after_charges.request_rights.description')

            .app-home-link-with-description
              = link_to t('home.after_charges.during_prosecution.link'), faqs_path(anchor: 'what-happens-during-prosecution-and-trial'),
                class: 'app-typography--body-1'
              .app-typography--body-2= t('home.after_charges.during_prosecution.description')

            .app-home-link-with-description
              = link_to t('home.after_charges.look_up_status.link'),
                'https://webportal.courts.oregon.gov/portal/Home/Dashboard/29',
                target: '_blank',
                class: 'app-typography--body-1'
              .app-typography--body-2= t('home.after_charges.during_prosecution.description')

        .row.app-row--left-line-dot
          .col.s8.offset-s2
            %h3.app-typography--header-1= t('home.after_closed.header')

            .app-home-link-with-description
              = link_to t('home.after_closed.look_up_status.link'), offenders_path, class: 'app-typography--body-1'
              .app-typography--body-2= t('home.after_closed.look_up_status.description')

            .app-home-link-with-description
              = link_to t('home.after_closed.after_sentencing.link'),
                faqs_path(anchor: 'what-happens-after-sentencing'),
                class: 'app-typography--body-1'
              .app-typography--body-2= t('home.after_closed.after_sentencing.description')

            .app-home-link-with-description
              = link_to t('home.after_closed.look_up_case.link'),
                'https://webportal.courts.oregon.gov/portal/Home/Dashboard/29',
                target: '_blank',
                class: 'app-typography--body-1'
              .app-typography--body-2= t('home.after_closed.look_up_case.description')

    .app-header
      .app-container.app-container--subhero.app-container--centered
        .row
          .col.s8.offset-s2
            %h3.app-typography--display-2= t('home.other_questions')

          .col.s8.offset-s2.m4.offset-m4
            .app-button-group
              = render_component 'button', stretch: true, to: faqs_path do
                = t('home.read_faqs')
              = render_component 'button', stretch: true, to: 'mailto:team@casecompanion.org' do
                = t('home.email_us')

    .app-header
      .app-container.app-container--subhero.app-container--centered
        .row
          .col.s10.offset-s1.m8.offset-m2
            %h3.app-typography--display-2= t('home.about_site')
            %p.app-typography--body-1
              - cfa_link = link_to('Code for America', 'https://www.codeforamerica.org', target: '_blank')
              = raw(t('home.description', cfa_link: cfa_link, product_name: product_name))

          .col.s10.offset-s1.m8.offset-m2
            = image_tag 'img_partner_seals.png', width: '100%'

    %main.app-container
      - if flash[:info]
        .row
          .col.s12
            = simpler_format flash[:info]
            = mixpanel_track_message :info, flash[:info]

      - if flash[:error]
        .row
          .col.s12.app-cell--error
            = simpler_format flash[:error]
            = mixpanel_track_message :error, flash[:error]

      = yield

    = render 'layouts/footer'

app/views/layouts/styleguide.html.haml
!!! 5
%html.app-layout--styleguide
  %head
    %title Case Companion
    = csrf_meta_tags

    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    %link{ href: '//fonts.googleapis.com/css?family=Roboto:300,400,500,700', rel: 'stylesheet' }

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'styleguide', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/analytics_js'

  %body
    .styleguide-container
      = yield